version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            python -m tests.unit_tests
      - run:
          name: deploy to heroku
          command: |
            git push https://heroku:$30b61314-bb52-43e2-9dc7-741553c815e0@git.heroku.com/$dry-depths-52773.git master